name: game2048
description: "Game 2048"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.0
  flutter_web_plugins:
    sdk: flutter
  audioplayers: 6.0.0
  flutter_hooks: ^0.20.0
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.2.3
  macos_ui: ^2.0.0
  macos_window_utils: ^1.5.0
  flutter_local_notifications: ^17.2.0
  super_clipboard: ^0.8.0
  platform_local_notifications: ^1.0.0
  # flutter_webview only for Android/iOS
  #  flutter_inappwebview:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^12.0.0

ffigen:
  output: 'lib/interop/desktop/generated_bindings.dart'
  headers:
    entry-points:
      - 'ffi/utils.h'

flutter:
  uses-material-design: true

  assets:
    - assets/pkg/
    - assets/Sakura-Girl-Daisy-chosic.com_original.mp3
    - assets/A.Cooper-LastTrack.mp3
    - assets/65733__erdie__bow01.mp3
    - assets/682635__bastianhallo__magic-spell.mp3
    - assets/fail_stamp.jpg
  shaders:
    - shaders/fire.frag
