name: game2048
description: "Game 2048"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  go_router:
  flutter_web_plugins:
    sdk: flutter
  audioplayers:
  flutter_hooks: ^0.20.0
  universal_platform: ^1.0.0+1
#  flutter_local_notifications:
  # flutter_webview only for Android/iOS
  #  flutter_inappwebview:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fail_stamp.jpg
    - assets/Sakura-Girl-Daisy-chosic.com_original.mp3
    - assets/A.Cooper-LastTrack.mp3
    - assets/65733__erdie__bow01.mp3
    - assets/682635__bastianhallo__magic-spell.mp3
  shaders:
    - shaders/fire.frag
