apiVersion: v1
kind: Service
metadata:
  name: game
  namespace: game2048
spec:
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  namespace: game2048
  labels:
    app: game
spec:
  selector:
    matchLabels:
      app: game
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: game
        octopusexport: OctopusExport
    spec:
      containers:
        - name: nginx
          image: dmitriizolotov2/2048
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game2048
  namespace: game2048
spec:
  ingressClassName: gitlab-nginx
  rules:
  - host: 2048.dzolotov.tech
    http:
      paths:
      - backend:
          service:
            name: game
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - 2048.dzolotov.tech
    secretName: wildcard
status:
  loadBalancer:
    ingress:
    - ip: 51.250.22.41
